---
engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  git-legal:
    # Looks like there needs to be a subscription to Git Legal Pro for this
    # config to be effective, so for now, leave this engine off, and depend
    # on the integration directly with Git Legal on pull requests.
    enabled: false
    config:
      # For the resume gem itself
      allow_unknown_libraries: true
      license_whitelist: ["GNU General Public License 3.0"]
  rubocop:
    # 20190209 NOTE: The version of Rubocop on Code Climate currently only
    # supports up to Ruby 2.5, while current Rubocop is up to 2.6, so for now,
    # disable old Rubocop on Code Climate.
    enabled: false
ratings:
  paths:
  - "Gemfile.lock"
  - "*.gemspec"
  - "**.rb"
exclude_paths:
- "spec/**/*"
