# Contains personal customisations of Rubocop default rules
require: rubocop-rspec

AllCops:
  Exclude:
    - "resume.rb"
    - "strings_en.rb"
    - "strings_it.rb"
    - "strings_ja.rb"
    # NOTE: Although this exclusion is in the default Rubocop config, it seems
    # that CI still goes looking in the vendor directory and attempts to
    # scan all files in all gems, so make the exclusion explicit here.
    - "vendor/**/*"
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  ExcludedMethods:
    - "before"
    - "configure"
    - "context"
    - "describe"
    # NOTE: Re-enable this when Code Climate Rubocop version updates
    # - "new"

Metrics/MethodLength:
  Max: 16

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*.rb"
    - "resume.rb"

RSpec/ExampleLength:
  # NOTE: Pretty much the fault of the FontExtractor module needing to mock
  # out the entirety of its interactiion with Zip::File
  Max: 10

# NOTE: RSpec cop seems to ignore the AllCops directive and complains that
# the resume.rb file isn't a *_spec.rb file, so suppress that issue.
RSpec/FilePath:
  Exclude:
    - "resume.rb"

RSpec/MultipleExpectations:
  Max: 5

# NOTE: This deep nesting mostly due to the wide range of paths that gem
# installation and file fetching can take, and the different errors that
# can occur.
RSpec/NestedGroups:
  Max: 8

Style/CaseEquality:
  # NOTE: This is rule is disabled, but care should be made to
  # *only ever* use `===` in `case` statements.
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

# NOTE: This cop is only disabled due to build-related issues on Windows
# via Appveyor.
Style/EndOfLine:
  Enabled: false

Style/FirstArrayElementLineBreak:
  Enabled: true

Style/FirstHashElementLineBreak:
  Enabled: true

Style/FirstMethodArgumentLineBreak:
  Enabled: true

Style/FirstMethodParameterLineBreak:
  Enabled: true

# NOTE: PDF generation requires string mutation, so this can't be used for now.
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/InlineComment:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: new_line

Style/MultilineMethodCallIndentation:
  Exclude:
    - "spec/**/*"
    - "resume.rb"

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringMethods:
  Enabled: true

Style/SymbolArray:
  Enabled: true
