tools:
  rubocop:
    use_native_config: true
filter:
  excluded_paths:
    - spec/*
    - vendor/*
build:
  dependencies:
    before:
      - cd /home/scrutinizer/.rbenv/plugins/ruby-build && git pull origin master && cd -
      - rbenv install -l
      -
        command: rbenv install 2.5.1
        idle_timeout: 600
      - rbenv local 2.5.1
      - ruby -v
      # - gem update --system
      # - gem install bundler i18n rspec
      - gem install i18n rspec
  environment:
    # ruby: 2.5.1
    ruby: 2.4.2
  nodes:
    analysis:
      tests:
        override:
          - rubocop-run --config .rubocop.yml
          - ruby-scrutinizer-run
  tests:
    before:
      - bin/bundle-audit check --update
      - bin/license_finder
      - bin/rubocop --display-cop-names
      - printf "yes\nno\n" | bin/resume
      - bin/resume -l it <<< "no\n"
      - printf "yes\nno\n" | bin/resume -l ja
      - bin/rake resume
      - ruby resume.rb <<< "no\n"
      - ruby resume.rb -l it <<< "no\n"
      - ruby resume.rb -l ja <<< "no\n"
    override:
      -
        command: bin/rspec spec/ --no-drb --format progress
        environment:
          'SCRUTINIZER_CC_FILE': 'my-coverage'
          # Scrutinizer cracked down on the possible versions used in the
          # `environment.ruby` variable, so make the build run on the highest
          # possible version available on their systems.
          # 'CUSTOM_RUBY_VERSION': '2.4.2'
        coverage:
          file: 'my-coverage'
          format: 'rb-cc'
      - rubocop-run --config .rubocop.yml
checks:
  ruby:
    code_rating: true
    duplicate_code: true
