# Base config taken from https://www.appveyor.com/docs/lang/ruby/#installation
version: 1.0.{build}-{branch}
cache:
  - vendor/bundle
skip_tags: true
build: off
environment:
  matrix:
    - ruby_version: 25
install:
  # If AppVeyor doesn't keep up and support the latest Ruby versions, then
  # uncomment the statement below and add a custom Ruby version.
  - SET CUSTOM_RUBY_VERSION=2.5.0
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby -e "puts RUBY_PLATFORM"
  # Get around the error
  # OpenSSL::SSL::SSLError:
  #   SSL_connect returned=1 errno=0 state=error: certificate verify failed
  # that occurs when trying to go and fetch a file remotely.
  # See https://gist.github.com/fnichol/867550#the-manual-way-boring
  - choco install wget
  - wget https://curl.haxx.se/ca/cacert.pem -O C:\cacert.pem
  - set SSL_CERT_FILE=C:\cacert.pem
  - gem update --system
  - gem install i18n rspec
  # Cache gems: https://www.appveyor.com/docs/lang/ruby/#caching
  # - bundle config --local path vendor/bundle
  - bundle install
before_test:
  - ruby -v
  - gem -v
  - bundle -v
test_script:
  # NOTE: We can't run Unix executables under Windows,
  # so call them directly using Ruby.
  - ruby bin/bundle-audit check --update
  - ruby bin/license_finder
  - ruby bin/rspec spec/ --no-drb --format progress
  - ruby bin/rubocop --display-cop-names
  - printf "yes\nno\n" | ruby bin/resume
  - printf "no\n" | ruby bin/resume -l it
  - printf "yes\nno\n" | ruby bin/resume -l ja
  - ruby bin/rake resume
  - printf "no\n" | ruby resume.rb
  - printf "no\n" | ruby resume.rb -l it
  - printf "no\n" | ruby resume.rb -l ja
