# Base config taken from https://www.appveyor.com/docs/lang/ruby/#installation
version: 1.0.{build}-{branch}
cache:
  - vendor/bundle
skip_tags: true
build: off
environment:
  matrix:
    - ruby_version: 25
    # - ruby_version: 26
install:
  # If AppVeyor doesn't keep up and support the latest Ruby versions, then
  # set the CUSTOM_RUBY_VERSION flag to whatever the latest version it supports.
  # Check current supported Windows images here:
  # https://www.appveyor.com/docs/windows-images-software/#ruby
  # NOTE: 2.6 currently does not work and outputs the following error:
  # Bundler could not find compatible versions for gem "ruby":
  # In Gemfile:
  #  ruby (~> 2.6.1.0)
  #  rubocop (~> 0.52) was resolved to 0.67.2, which depends on
  #    psych (>= 3.1.0) was resolved to 3.1.0, which depends on
  #      ruby (< 2.6) x86-mingw32
  # Could not find gem 'ruby (< 2.6)', which is required by gem 'psych (>= 3.1.0)',
  - SET CUSTOM_RUBY_VERSION=2.5.5
  # If there are `Unable to download data from https://rubygems.org/` issues,
  # then add the current Appveyor Ruby version to the path.
  # https://help.appveyor.com/discussions/problems/15052-unable-to-download-data-from-httpsrubygemsorg
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - ruby -e "puts RUBY_PLATFORM"
  # Get around the error
  # `OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed`
  # that occurs when trying to go and fetch a file remotely.
  # See https://gist.github.com/fnichol/867550#the-manual-way-boring
  # NOTE: With RubyInstaller2 builds (Ruby version >= 2.4), the cert hack should
  # not be needed: https://www.appveyor.com/docs/lang/ruby/#openssl-verification
  # - choco install wget
  # - wget https://curl.haxx.se/ca/cacert.pem -O C:\cacert.pem
  # - set SSL_CERT_FILE=C:\cacert.pem
  # Updating system gems may return the following error:
  # `ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)`
  # `SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version`
  # In that case, just don't update the system gems.
  - gem update --system
  - gem install i18n rspec
  # Cache gems: https://www.appveyor.com/docs/lang/ruby/#caching
  # - bundle config --local path vendor/bundle
  - bundle install
before_test:
  - ruby -v
  - gem -v
  - bundle -v
test_script:
  # NOTE: We can't run Unix executables under Windows,
  # so call them directly using Ruby.
  - ruby bin/bundle-audit check --update
  - ruby bin/license_finder
  - ruby bin/rspec spec/ --no-drb --format progress
  - ruby bin/rubocop --display-cop-names
  - printf "yes\nno\n" | ruby bin/resume
  - printf "no\n" | ruby bin/resume -l it
  - printf "yes\nno\n" | ruby bin/resume -l ja
  - ruby bin/rake resume
  - printf "no\n" | ruby resume.rb
  - printf "no\n" | ruby resume.rb -l it
  - printf "no\n" | ruby resume.rb -l ja
