source "https://rubygems.org"
ruby ENV["CUSTOM_RUBY_VERSION"] || "2.7.2"

gem "i18n", "~> 1.0"
gem "prawn", "~> 2.3"
gem "prawn-table", "~> 0.2.2"
gem "rubyzip", "~> 2.3"

gem "awesome_print", "~> 1.8"
gem "bundler", "~> 2.0"
gem "bundler-audit", "~> 0.5"
gem "fuubar", "~> 2.4"
gem "guard-reek", "~> 1.0"
gem "guard-rspec", "~> 4.6"
gem "guard-rubocop", "~> 1.2"
gem "guard-yard", "~> 2.2"
gem "kramdown", "~> 2.1"
gem "pry-byebug", "~> 3.1"
gem "rake", "~> 13.0"
gem "reek", "~> 6.0"
gem "rspec", "~> 3.4"
gem "rubocop", "~> 1.0"
gem "rubocop-rake", "~> 0.6", require: false
gem "rubocop-rspec", "~> 2.0.0.pre"
gem "rubygems-tasks", "~> 0.2"
gem "simplecov", "~> 0.16"
gem "yard", "~> 0.9"
