version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler i18n rspec
      - run:
          command: bundle install
          no_output_timeout: 180s
      - run: bin/bundle-audit check --update
      - run: bin/license_finder
      - run: bin/rspec spec/ --no-drb --format progress
      - run: bin/rubocop --display-cop-names
      - run: bin/resume <<< "no\n"
      - run: bin/resume -l it <<< "no\n"
      - run: printf "yes\nno\n" | bin/resume -l ja
      - run: bin/rake resume
      - run: ruby resume.rb <<< "no\n"
      - run: ruby resume.rb -l it <<< "no\n"
      - run: ruby resume.rb -l ja <<< "no\n"
