$LOAD_PATH << File.join(File.dirname(__FILE__), 'resume_generator')

require 'colourable'
require 'cli'
require 'decodable'
require 'link'
require 'logo'
require 'image'
require 'resource'
require 'position'
require 'organisation'
require 'period'
require 'location'
require 'resume_helper'
require 'resume'
require 'version'
